module.exports = {
  id: 'voicenote',

  patches: [
    /* 인식 언어 기본값을 영어로 */
    ['<option value="ko-KR" selected>한국어</option>\n        <option value="en-US">English</option>',
     '<option value="en-US" selected>English</option>\n        <option value="ko-KR">한국어 (Korean)</option>'],

    /* 예시 사전을 영문 용어로 */
    ['placeholder="한 줄에 하나씩 · 잘못된말 → 고칠말">MNL\n측정\n전시회\n투자\n스타트업\n고중량\n상용화\n연구소\n로보틱스\n유료화</textarea>',
     'placeholder="One per line · misheard → correction">MNL\nSKU\nSaaS\nKubernetes\nAnthropic\nroadmap\nonboarding\nprocurement\nteh → the\nrecieve → receive</textarea>'],

    ["toast(langSel.value === 'ko-KR' ? '한국어로 인식합니다' : 'Recognizing in English');",
     "toast(langSel.value === 'ko-KR' ? 'Recognising in Korean' : 'Recognising in English');"],

    ["showWarn('한국어 인식 모델을 내려받고 있습니다. 용량이 커서 몇 분 걸릴 수 있습니다. 창을 닫지 마세요.');",
     "showWarn('Downloading the recognition model. It is a large file and may take a few minutes, so please keep this window open.');"],

    ["const name = '받아쓰기_' + d.getFullYear() + p(d.getMonth() + 1) + p(d.getDate()) +",
     "const name = 'dictation_' + d.getFullYear() + p(d.getMonth() + 1) + p(d.getDate()) +"]
  ],

  strings: [
    /* 환경 안내 */
    ["'file:// 로 연 페이지에서는 마이크 권한이 있어도 인식 결과가 오지 않습니다. 이 파일이 있는 폴더에서 터미널을 열고 python3 -m http.server 를 실행한 뒤,",
     "'Opened as a file:// page, recognition returns nothing even with microphone permission. Run python3 -m http.server in this folder and open it through localhost instead,"],
    ["'이 페이지가 미리보기 창(iframe) 안에 있습니다. 파일을 내려받아 브라우저 탭에서 직접 열어 주세요.'",
     "'This page is inside a preview frame. Open it directly in a browser tab instead.'"],
    ["'Brave는 구글 음성 인식 서버 연결을 기본 차단합니다. Chrome으로 열어 주세요.'",
     "'Brave blocks the speech recognition server by default. Please use Chrome.'"],
    ["'웨일 등 일부 크로미움 브라우저는 음성 인식 API 키가 없어 결과가 오지 않습니다. Chrome으로 열어 주세요.'",
     "'Some Chromium browsers ship without a speech API key and return no results. Please use Chrome.'"],
    ["'Edge는 Windows 설정 > 개인 정보 > 음성에서 온라인 음성 인식이 켜져 있어야 합니다.'",
     "'Edge needs online speech recognition enabled under Windows Settings > Privacy > Speech.'"],
    ["'Firefox는 이 기능을 지원하지 않습니다. Chrome으로 열어 주세요.'",
     "'Firefox does not support this feature. Please use Chrome.'"],
    ["'Safari는 지원이 제한적입니다. Chrome으로 열어 주세요.'",
     "'Safari support is limited. Please use Chrome.'"],
    ["'https 또는 localhost 에서만 동작합니다.'", "'This only works over https or on localhost.'"],
    ["'주소창 왼쪽 자물쇠에서 마이크 권한을 확인해 주세요.'",
     "'Check the microphone permission under the padlock in the address bar.'"],

    /* 경고 · 안내 */
    ['Web Speech API를 지원하지 않는 브라우저입니다. Chrome으로 열어 주세요. 직접 입력은 그대로 사용할 수 있습니다.',
     'This browser does not support the Web Speech API. Please use Chrome. Typing directly still works.'],
    ['음성은 정상적으로 들어오지만 인식 서버 응답이 없습니다. 아래 모델 설치 버튼으로 온디바이스 인식 모델을 내려받으면 서버 없이 동작합니다.',
     'Audio is arriving but the recognition server is not responding. Install the on-device model below and it will work without a server.'],
    ['음성은 정상적으로 들어오지만 인식 결과가 돌아오지 않습니다. ',
     'Audio is arriving but no recognition results are coming back. '],
    ['음성 인식 서버에 연결하지 못했습니다. 이 기능은 음성을 구글 서버로 보내 처리합니다. ',
     'Could not reach the speech recognition server. In this mode audio is sent to Google for processing. '],
    ['소리가 감지되지 않습니다. 시스템 입력 장치와 마이크 음소거 상태를 확인해 주세요.',
     'No sound detected. Check your input device and whether the microphone is muted.'],
    ['인식이 시작되자마자 반복해서 끊깁니다. ', 'Recognition keeps dropping as soon as it starts. '],
    ['인식 세션을 다시 연결하지 못했습니다. 마이크 버튼을 다시 눌러 주세요.',
     'The recognition session could not be reconnected. Press the microphone button again.'],
    ['서버 응답이 없어 짧게 끊어 인식하는 방식으로 다시 시도합니다.',
     'No server response, so retrying in short bursts instead.'],
    ['마이크 입력이 열리지 않습니다. ', 'The microphone did not open. '],
    ['마이크 사용이 차단되었습니다. ', 'Microphone access is blocked. '],
    ['마이크가 차단될 수 있는 환경입니다. ', 'The microphone may be blocked in this environment. '],
    ['먼저 인식 모델을 설치해야 합니다. 옆의 모델 설치 버튼을 눌러 주세요.',
     'The recognition model needs installing first. Use the install button beside this.'],
    ['이 브라우저는 모델 설치를 지원하지 않습니다.', 'This browser does not support installing the model.'],
    ['모델 설치가 완료되지 않았습니다. 잠시 후 다시 시도해 주세요.',
     'The model did not finish installing. Please try again shortly.'],
    ['설치가 완료로 보고됐지만 모델이 준비되지 않았습니다 (', 'Install reported success but the model is not ready ('],
    ['모델 설치에 실패했습니다 (', 'Model installation failed ('],
    ['). 크롬을 최신 버전으로 올린 뒤 다시 시도해 주세요.', '). Update Chrome and try again.'],
    ['음성 인식을 시작하지 못했습니다 (', 'Speech recognition would not start ('],
    ['). 새로고침 후 다시 시도해 주세요.', '). Reload and try again.'],
    ['선택한 언어를 이 브라우저가 지원하지 않습니다.', 'This browser does not support the selected language.'],
    ['음성 인식 오류 : ', 'Recognition error: '],
    ['모델 설치 완료. 온디바이스로 인식합니다', 'Model installed. Recognition now runs on your device.'],

    /* 화면 */
    ['자주 쓰는 고유명사·전문용어를 한 줄에 하나씩 적으면, 비슷하게 인식된 말을 그 단어로 바로잡습니다.',
     'List the names and technical terms you use often, one per line, and similar sounding results are corrected to them.'],
    ['확실한 오인식은 <span class="text-ink">잘못된말 → 고칠말</span> 형식으로 지정할 수 있습니다.',
     'For a mistake you see repeatedly, write <span class="text-ink">misheard → correction</span>.'],
    ['마이크 버튼을 누르고 말하거나, 여기에 직접 입력하세요',
     'Press the microphone and speak, or just type here'],
    ['인식된 임시 문장이 여기에 회색으로 표시됩니다', 'Interim results appear here in grey'],
    ['말한 내용을 받아 적는 작업대 · 저장되지 않음',
     'A workbench for turning speech into text · nothing is stored'],
    ['브라우저가 막았습니다. Ctrl+A → Ctrl+C를 사용하세요',
     'The browser blocked copying. Use Ctrl+A then Ctrl+C.'],
    ['작성된 내용을 모두 지웁니다. 계속할까요?', 'This clears everything you have written. Continue?'],
    ['브라우저가 다운로드를 막았습니다', 'Your browser blocked the download'],
    ['이 브라우저는 음성 인식을 지원하지 않습니다', 'This browser does not support speech recognition'],
    ['워드용으로 복사되었습니다!', 'Copied for Word'],
    ['음성 인식 노트패드', 'Voice Notepad'],
    ['모델 내려받는 중', 'Downloading model'],
    ['음성 인식 시작', 'Start recognition'],
    ['음성 인식 중지', 'Stop recognition'],
    ['추천 단어 사전', 'Correction dictionary'],
    ['한 줄에 하나씩 · 잘못된말 → 고칠말', 'One per line · misheard → correction'],
    ['다시 누르면 중지', 'Press again to stop'],
    ['누르면 인식 시작', 'Press to start'],
    ['복사·저장 형식', 'Copy and save format'],
    ['복사 형식', 'Copy format'],
    ['워드·한글용', 'For Word'],
    ['메모장용', 'Plain text'],
    ['한 문단으로', 'Single paragraph'],
    ['실시간 교정', 'Correct as I speak'],
    ['전체 다듬기', 'Clean up all'],
    ['인식 언어', 'Recognition language'],
    ['온디바이스', 'On-device'],
    ['모델 설치', 'Install model'],
    ['내려받는 중', 'Downloading'],
    ['진단 기록', 'Diagnostics'],
    ['받아쓰기</span>', 'Dictation</span>'],
    ['대기 중', 'Idle'],
    ['인식 중', 'Listening'],
    ['정확도', 'Accuracy'],
    ['엄격', 'Strict'],
    ['보통', 'Normal'],
    ['느슨', 'Loose'],
    ['전체 복사', 'Copy all'],
    ['초기화', 'Reset'],
    ['저장', 'Save'],
    ['공백 포함', 'with spaces'],
    ['공백 제외', 'without spaces'],
    ['다듬을 내용이 없습니다', 'Nothing to clean up'],
    ['복사할 내용이 없습니다', 'Nothing to copy'],
    ['저장할 내용이 없습니다', 'Nothing to save'],
    ['고칠 부분이 없습니다', 'Nothing needed changing'],
    ['복사되었습니다!', 'Copied'],
    ['저장되었습니다!', 'Saved'],
    ["'교정 ' + changes.length + '건 · '", "changes.length + ' corrections · '"],
    ["r.changes.length + '건 교정했습니다'", "r.changes.length + ' corrections made'"],
    ["'교정 · ' + r.changes.join(', ')", "'corrected: ' + r.changes.join(', ')"],
    ['개</span>', '</span>'],
    ['class="num ml-1 text-ink">0</span>개', 'class="num ml-1 text-ink">0</span>'],
    [' 크롬에서 http://localhost:8000/voice-notepad.html 로 접속해 주세요.',
     ' then open http://localhost:8000/voice-notepad.html in Chrome.'],

    /* 진단 로그 */
    ['보안 컨텍스트 ', 'secure context '],
    ['주소 ', 'protocol '],
    ['온라인 ', 'online '],
    ['세션 재시작 #', 'session restart #'],
    ['재시작 실패 · ', 'restart failed · '],
    ['시도 ', 'attempt '],
    ['12초간 무응답 → 강제 재연결', 'no response for 12s, forcing reconnect'],
    ['탭 복귀 → 세션 재연결', 'tab refocused, reconnecting session'],
    ['온디바이스 인식 지원됨', 'on-device recognition supported'],
    ['온디바이스 모델(', 'on-device model ('],
    [') 상태 · ', ') state · '],
    ['모델 상태 확인 실패 · ', 'model state check failed · '],
    ['모델 설치 시작 · ', 'model install started · '],
    ['설치 결과 · ', 'install result · '],
    ['설치 후 재확인 · ', 'recheck after install · '],
    ['설치 실패 · ', 'install failed · '],
    ['사용 가능', 'available'],
    ['없음', 'unavailable'],
    ['온디바이스 모드로 시작', 'starting in on-device mode'],
    ['경고 : audiostart 없음', 'warning: no audiostart'],
    ['마이크 열림', 'microphone open'],
    ['소리 감지', 'sound detected'],
    ['음성 감지', 'speech detected'],
    ['결과 없음 → continuous 끄고 재시도', 'no results, retrying without continuous'],
    ['폴백 후에도 결과 없음', 'still no results after fallback'],
    ['인식 실패', 'no match'],
    ["'onresult · 확정 ' + finals + '건, 임시 ' + interim.length + '자'",
     "'onresult · ' + finals + ' final, ' + interim.length + ' interim chars'"],
    ['자동 재시작', 'auto restart'],
    ['start() 호출', 'start() called'],
    ['start() 예외 · ', 'start() threw · '],
    ['사용자 중지', 'stopped by user'],
    ['응답 없어 강제 종료', 'no response, aborting'],
    ['언어 변경 · ', 'language changed · ']
  ],

  guide: {
    intro: {
      h: 'Sometimes speaking is faster than typing',
      p: [
        'An idea arrives while you are walking. A meeting needs a note taken in real time. Your hands are busy. Dictation services handle all of these, but almost all of them send the audio to a server, which is a problem when the recording is a client conversation or an internal meeting.',
        'This tool can download a speech model into your browser and run recognition on your device. After the one time install, your audio never leaves your machine. There is also a correction dictionary for the names and technical terms that recognition consistently gets wrong.'
      ]
    },
    uses: [
      { t: 'Meeting notes', d: 'Capturing points as they come up, without the recording leaving your device.' },
      { t: 'Ideas while moving', d: 'Getting a thought down when typing is not practical.' },
      { t: 'First drafts of long writing', d: 'Talking through the material and shaping it afterwards. It gets past a blank page faster than typing does.' },
      { t: 'Domain-heavy vocabulary', d: 'Add the terms that keep coming out wrong to the dictionary and they are corrected automatically from then on.' }
    ],
    steps: [
      'For on-device recognition, press <strong>Install model</strong> once and wait for the download.',
      'Press the microphone and speak. You can type alongside it at any time.',
      'Add repeated mistakes to the dictionary as <strong>misheard → correction</strong>.',
      'Use <strong>Clean up all</strong> to tidy the text, then copy it.'
    ],
    options: [
      { t: 'Accuracy: strict, normal, loose', d: 'How cautious the matching is. Strict is more accurate and slower, loose is quicker with more mistakes.' },
      { t: 'Recognition language', d: 'English by default. Setting the right language noticeably improves accuracy.' },
      { t: 'On-device', d: 'Runs recognition locally once the model is installed, so no audio is sent anywhere.' },
      { t: 'Correction dictionary', d: 'Names and technical terms you use often. Stored in your browser, so it is still there next visit.' }
    ],
    faq: [
      { q: 'Is my audio sent to a server', a: 'With the on-device model installed, no. The model is downloaded once and recognition happens in your browser. Without it, the browser\'s built-in recognition does route audio through a speech service, which is why the on-device option exists.' },
      { q: 'Why does the model take so long to install', a: 'It is a large file, so a few minutes is normal depending on your connection. Once downloaded it stays in your browser and starts instantly after that.' },
      { q: 'Which browser should I use', a: 'Chrome is the most reliable. Firefox does not support the API at all, Safari support is limited, and Brave blocks the speech server by default.' },
      { q: 'Recognition is poor. What can I do', a: 'Set accuracy to strict, get closer to the microphone and speak deliberately. If one particular word keeps failing, put it in the dictionary rather than fighting the recogniser.' }
    ]
  }
};
